@startuml

start
:Извлечь тест и вопросы из базы данных;
:Извлечь данные о попытке сдачи теста;
:Собрать все активные ответы;
repeat: Перебор активных ответов
  :Прочитать ответ;
  :Сверить ответ с верным;
  :Оценить ответ;
  :Вычислить балл в соответствии с политикой;
  :Сформировать оценку за ответ, 
  сложить в буфер;
backward: Взять следующий ответ;
repeat while (Есть ещё ответы?)
:Сложить баллы из всех оценок;
if (Проходной балл набран) then (Да)
    :Тест пройден;
else (Нет)
    :Тест не пройден;
endif
:Сохранить все оценки;
:Сохранить итоговый балл;
:Сохранить итог проверки и время завершения;
stop
@enduml