@startuml AlphaTest context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(admin, "Администратор", "Управляет учетными записями, обрабатывает заявки пользователей")
Person(teacher, "Преподаватель", "Составляет тесты, проводит экзамены, проверяет работы")
Person(student, "Учащийся", "Сдаёт тесты на оценку")
System(alphatest, "Система тестирования «АльфаТест»", "Предоставляет функциональность по составлению тестов, прохождению тестирования, управлению доступом для пользователей, а также по ручной и автоматической проверке работ")
System_Ext(mail_service, "Сервис отправки e-mail", "Осуществляет отправку транзакционных писем пользователям")

Rel(admin, alphatest, "Управление учетными записями, обработка заявок")
Rel(teacher, alphatest, "Составление тестов, проверка работ учащихся")
Rel(student, alphatest, "Выполнение заданий")
Rel(teacher, admin, "Отправка заявок (напр. подтвердить публикацию теста)")


Rel(alphatest, mail_service, "Использует для отправки оповещений")

SHOW_LEGEND()

@enduml