@startmindmap
* AlphaTest
** Составление тестов
*** Просмотр списка тестов
*** Создание теста
*** Редактирование теста
**** Изменение настроек проведения теста
**** Работа со списком вопросов
***** Добавление/удаление/редактирование вопроса
***** Изменение порядка вопросов в тесте
*** Списание теста в архив
*** Создание новой редакции теста
*** Управление доступом к тесту
**** Добавить составителя
**** Выйти из числа составителей
**** Отправка заявки на исключение составителя
**[#Orange] Работа с учебными группами
**[#Orange] Проведение экзаменов
*** Планирование экзамена
*** Просмотр списка экзаменов
** Сдача тестирования
*** Просмотр списка доступных тестов
*** Выполнение задания
**** Просмотр информации о сдаваемом тесте
**** Просмотр списка вопросов
**** Просмотр информации о вопросе
**** Переход между вопросами
**** Ответы на вопросы
***** Отправка ответа
***** Отзыв ответа
***** Повторная отправка
**** Завершение тестирования
** Просмотр результатов тестирования
** Проверка работ
*** Просмотр списка непроверенных работ
*** Ручная проверка работы преподавателем
*** Автоматическая проверка работы
**[#Orange] Отчётность
**[#Orange] Управление учётными записями
**[#Orange] Отправка уведомлений
*** Студентам
**** О предоставлении доступа к системе
**** О начале экзамена
**** О проверке сданной работы
***[#Orange] Преподавателям
**** О предоставлении доступа к системе
**** О включении/исключении в список составителей
**** О наличии непроверенных работ
***[#Orange] Администраторам
@endmindmap