@startmindmap
* AlphaTest
** Составление тестов
*** Просмотр списка тестов
*** Создание теста
*** Редактирование теста
**** Изменение настроек проведения теста
**** Работа со списком вопросов
***** Добавление/удаление/редактирование вопроса
***** Изменение порядка вопросов в тесте
*** Списание теста в архив
*** Создание новой редакции теста
*** Управление доступом к тесту
**** Добавление составителя
**** Выход из числа составителей
**** Исключение преподавателя из списка составителей
**** Передача тест другому преподавателю
** Работа с учебными группами
*** Просмотр списка групп
*** Создание группы
*** Расформирование группы
*** Изменение состава группы (добавление/исключение учащихся)
*** Назначение куратора группы
** Проведение экзаменов
*** Просмотр списка экзаменов
*** Назначение экзамена
*** Перенос сроков экзамена
*** Отмена экзамена
** Сдача тестирования
*** Просмотр списка доступных экзаменов
*** Выполнение задания
**** Просмотр информации о сдаваемом тесте
**** Просмотр списка вопросов
**** Просмотр информации о вопросе
**** Переход между вопросами
**** Ответы на вопросы
***** Отправка ответа
***** Отзыв ответа
***** Повторная отправка
**** Завершение тестирования
** Просмотр результатов тестирования
** Проверка работ
*** Просмотр списка непроверенных работ
*** Ручная проверка работы преподавателем
*** Автоматическая проверка работы
**[#Orange] Отчётность
**[#Orange] Управление учётными записями
*** Ввод данных о пользователях
*** Массовый импорт сведений об учащихся
*** Назначение ролей доступа пользователям
*** Блокировка учётной записи
** Отправка уведомлений
*** Студентам
**** О предоставлении доступа к системе
**** О начале экзамена
**** О проверке сданной работы
*** Преподавателям
**** О предоставлении доступа к системе
**** О включении/исключении в список составителей
**** О передаче прав на тест
**** О наличии непроверенных работ
**** О назначении куратором группы
*** Администраторам
**** О предоставлении доступа к системе
**** О наличиии необработанных заявок
@endmindmap