@startuml
Черновик : Можно редактировать
Черновик : Можно отправить заявку
ОтправленаЗаявка : Нельзя редактировать
Опубликован : Нельзя редактировать
Опубликован : Можно проводить экзамены
Архив : Недоступен

[*] --> Черновик
Черновик --> ОтправленаЗаявка : Отправка заявки
ОтправленаЗаявка --> Опубликован : Заявка одобрена
ОтправленаЗаявка --> Черновик : Заявка отклонена
Опубликован--> Архив : Создана новая редакция (старый тест)
Опубликован--> Черновик : Создана новая редакция (новый тест)
@enduml